const Types = {
  CURRENCY: "CURRENCY",
  CURRENCY_ID: "CURRENCY_ID",
  CURRENCY_SYMBOL: "CURRENCY_SYMBOL",
  CATEGORIES: "CATEGORIES",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  CART_CONTENT: "CART_CONTENT",
  CART_ADD_ITEM: "ADD_TO_CART",
  CHECK_OUT: "CHECK_OUT",
  PRODUCT_AMOUNT: "PRODUCT_AMOUNT",
  CART_AMOUNT: "CART_AMOUNT",
  START_CART_AMOUNT: "START_CART_AMOUNT",
};

export default Types;